### ISSUE TITLE
Repair doesn't work reliable

### ISSUE THREAD

**Issue by sperrgebiet** [sperrgebiet/FS19_VehicleExplorer#2]
For most of the vehicles repair doesn't work. Sometimes I see that some money was deducted from the account, but the wear seems to stay the same.

**Comment by neooblaster** [comment]
Hi Sperrgebiet ! Huge thanks for VeXe !
The repair function you are speaking in this issue is the LALT + R feature ?
On my side, with default vehicule, nothing happens.

Kindly Regards,
Neoblaster

**Comment by sperrgebiet** [comment]
Hi. Please check the latest version, 0.9.0.5. This should work now fine. Made a stupid mistake, that was the reason why it tried to repair vehicles which were actually not selected :)

Give it a try and report back please. For me it worked fine before.

Cheers
_Hans

**Comment by neooblaster** [comment]
Hi Hans

I tried the v0.9.0.5. The keybinding LALT+R works perfectly now !
You can close this issue !

On which website you publish your mod ?

Kindly Regards,
Nicolas D.

**Comment by sperrgebiet** [comment]
Hi Nicolas

Thanks for the confirmation. Will close this then for now.

I've uploaded it so far to modhoster, ls-portal & modhub.us. But all of them usually take quite a while to get a new build released. So the best is to check here on GitHub, as I always build a ZIP once issues are fixed or new features are added. As it was the case just a couple of minutes ago.

Deep link to the ZIP: https://github.com/sperrgebiet/FS19_VehicleExplorer/blob/master/FS19_VehicleExplorer.zip?raw=true

HTH
_Hans

**Comment by neooblaster** [comment]
Hi _Hans,

Maybe I found a new issue related to this fix but I not sure.
Before modification, `Wear` information was correct with another mod.
Now, you replaced by `damage`, but values are differents : 
`Wear`is the current health of the vehicle and `damage`are the pourcentage which affect efficiency ?

![image](https://user-images.githubusercontent.com/22078558/52882715-e03d8a00-3168-11e9-84f0-522a882ab6fb.png)

Another point as feedback. LALT+R only works on the first implement.
Hereafter, on tractor with 3 trailers. Only the tractor and the first trailer has been repaired.
I remember to see many implements before updating. Maybe you introduce a regression.

![image](https://user-images.githubusercontent.com/22078558/52883248-935ab300-316a-11e9-9dfe-5e729466a9a4.png)


Best Regards,
Nicolas D.
